encoding: UTF-8
exclude:
- Gemfile
- Gemfile.lock
- Makefile
- notes.md

permalink: /:title
safe: false

author: Mitja Felicijan
domain: https://mitjafelicijan.com/
description: Embedded systems developer and fanatical fan of science fiction
twitter: "@mitjafelicijan"
avatar: assets/avatar.gif
cache_version: 20180803
theme_color: "#c242f4"

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     true
  footnote_nr:   1
  show_warnings: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

plugins:
- jekyll-sitemap
