encoding: UTF-8
exclude:
- Gemfile
- Gemfile.lock
#kramdown:
#  input: GFM
#  hard_wrap: false
#future: true
#jailed: false

#highlighter: rouge
markdown: kramdown

permalink: /:title

#plugins:
#- jekyll-minifier
