encoding: UTF-8
exclude:
- Gemfile
- Gemfile.lock
- Makefile
- notes.md

permalink: /:title

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     false
  footnote_nr:   1
  show_warnings: false
  syntax_highlighter: rouge

highlighter: rouge

#plugins:
#- jekyll-minifier
