encoding: UTF-8
exclude:
- Gemfile
- Gemfile.lock
- Makefile
- notes.md

author: Mitja Felicijan
description: Embedded systems developer and fanatical fan of science fiction

permalink: /:title

kramdown:
  auto_ids:      true
  entity_output: as_char
  toc_levels:    1..6
  smart_quotes:  lsquo,rsquo,ldquo,rdquo
  input:         GFM
  hard_wrap:     true
  footnote_nr:   1
  show_warnings: false
  syntax_highlighter: rouge

plugins:
  - jekyll-sitemap
  - jekyll-minifier
  - jekyll-jsminify
