baseURL = 'https://mitjafelicijan.com/'
languageCode = 'en-us'
title = 'Mitja Felicijan'

# Theme selction.
theme = 'simple'

# Makes url's have '.html' at the end.
uglyurls = true

# Length of summary.
summaryLength = 5

# Enabling robots.txt.
enableRobotsTXT = true

# Custom params.
[params]
  description = 'You do not learn by relaxing. You learn by violently assaulting your problem until it surrenders its mysteries to you.'

# URL if not specified in a post or a page.
[permalinks]
  posts = ':title'
  pages = ':title'

# Author information.
[author]
  name = 'Mitja Felicijan'

# Additional markup settings.
[markup]
  [markup.tableOfContents]
    endLevel = 5
    ordered = false
    startLevel = 2

  [markup.goldmark.renderer]
    unsafe = true

  [markup.highlight]
    style = 'github'

# Taxonomies.
[outputs]
  index = ["HTML", "atom"]
  section = ["HTML", "notes"]

# Output formats.
[outputFormats]
  [outputFormats.atom]
    mediatype = "application/rss"
    rel = "atom"
    baseName = "atom"
  [outputFormats.notes]
    mediatype = "application/rss"
    rel = "notes"
    baseName = "notes"
